name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - rasterio
  - xarray
  - numpy
  - netcdf4
  - dask
  - scipy
  - yaml
  - pandas
  - scikit-learn
  - conda-build
  - ca-certificates
  - certifi
  - openssl
  - ncl
  - gdal
  - fiona
  - rtree
  - python=3.9
  - geopandas
  - earthengine-api
  - google-cloud-sdk